### ISSUE TITLE
Doc mistake

### ISSUE THREAD

**Issue by LupusVII** [dansmaculotte/monetico-php#16]
Hello !
Thanks for the V2 :D
There is a tiny issue in the doc: Monetico needs the country in ISO 3166-1 alpha-2 format.
Instead of "France", it should be "FR" and it will be perfect :)
See you!

**Comment by hmonglee** [comment]
https://github.com/dansmaculotte/monetico-php/pull/18

**Comment by gaelreyrol** [comment]
I merged your PR @hmonglee !
