### ISSUE TITLE
validateSeal case & double quote required

### ISSUE THREAD

**Issue by LupusVII** [DansMaCulotte/monetico-php#2]
Hello !
First, many thanks for this library. It's tiny but pretty useful.

I found two tiny issues in the code I fixed :

1. The seal statement compare an uppercase string with a lowercase string, so it always return false even if the hmac is correct. (src/Payment/Response.php - l.325)
Solution : strtolower the object seal :
```php
return $hash == strtolower($this->seal);
```

2. The receipt syntax is wrapped by single quotes (src/Payment/Receipt.php - l.7) which means the \n isn't understood well.
Solution : change to double quotes :
```php
const OUPUT_FORMAT = "version=2\ncdr=%s\n";
```

I've made the changes on my side and it works perfectly.
Thanks again for your work !

**Comment by Zevran** [comment]
Thanks for pointing theses errors ! I am working on it.
