### ISSUE TITLE
Implement 3DSv2

### ISSUE THREAD

**Issue by LupusVII** [DansMaCulotte/monetico-php#3]
Hi !
Maybe you received the notification but Monetico will upgrade its services in September 2019. Here is the doc : https://www.monetico-paiement.fr/fr/info/documentations/Monetico_Paiement_documentation_migration_3DSv2_1.0.pdf

There is a change about the parameters to send and a new way to calculate MAC. If I get the time to do it in the summer and you haven't done it earlier, I'll make a fork of your repo and update it for these new rules !

Regards,

**Comment by Zevran** [comment]
Hi @LupusVII

Thanks for the update, I will update it as soon as possible with @martinpotel in the coming weeks but if you need those changes before don't hesitate to submit a pull request !

Regards

**Comment by Zevran** [comment]
Here is the now documentation to use: https://www.monetico-paiement.fr/fr/info/documentations/Monetico_Paiement_documentation_technique_v2.0.pdf
