### ISSUE TITLE
Question pratique DSP2

### ISSUE THREAD

**Issue by LrntL** [dansmaculotte/monetico-php#32]
Bonjour,

Je suis désolé de poser la question ici mais comme vous êtes hyper calés concernant Monetico...

Dans le cadre de la nouvelle directive DSP2, Monetico exige la saisie de l'adresse complète du porteur de carte pour renforcer la sécurité. 

Mon problème est le suivant : Je vends en ligne des préventes de billetterie, je n'ai donc aucunement besoin de l'adresse de facturation mais leur système oblige la saisie ce qui, vous en conviendrez, rend le processus de commande vraiment nul ! (L'acheteur prend ses préventes, on demande son nom car elles sont nominatives et ensuite, je suis obligé de mettre un pavé "Qui effectue le paiement ?" pour qu'il renseigne le nom, prénom, adresse, cp, ville et pays du porteur de la carte pour seulement après générer l'iFrame Monetico (Ca arrive qu'ils prennent la carte des parents pour payer par exemple...).

J'ai l'impression que ceux sont les seuls à faire cela. C'est vraiment "nul", sachant que derrière il y a encore le 3D Secure avec authentification de l'acheteur via SMS/Code ou Application de la banque.

C'est d'autant plus contraignant, que je propose le paiement à plusieurs, donc chaque participant au paiement doit lui aussi saisir toutes ces informations !

N'y a-t-il aucun moyen de faire autrement ?
Par avance merci pour vos conseils.

**Comment by rtouze** [comment]
Bonjour,

N'étant pas juriste, je ne sais pas trop quoi vous dire :sweat_smile: . Je ne travaille pas pour Monetico.
Si Monetico vous demande de saisir une adresse de facturation pour effectuer le paiement, vous n'avez pas trop le choix. Dans le cadre de la DSP2, je pense qu'ils demandent ces informations pour éviter les paiements frauduleux. Je vous invite tout de même à solliciter votre contact commercial à ce propos et à changer de prestataire pour le paiement si cela ne vous convient pas.
